name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build --tag lambda-ecr-repo:${{ github.run_number }} .
        
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: lambda-ecr-repo:${{ github.run_number }}
          
  lambda_update:
    name: Deploy lambda
    needs: build
    runs-on: ubuntu-latest
    env:
      FUNCTION_NAME: lambda_function
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    
    steps:
      - name: job dependencies
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          
      - name: update
        run: |
          aws lambda update-function-code \
            --function-name ${FUNCTION_NAME} \
            --image-uri ${{ secrets.AWS_ECR_URL }}:${{ github.run_number }}
            